meta:
  data_name: "ae_mnist"
  experiment_name: "trial_00"
  start_fresh: False

logging:
  console:
    level: "info"
    format_str: null
  file:
    level: "ERROR"
    format_str: null
  track:
    tracker_steps: 30
    tensorboard:
      param_steps: 50

performance:
  objectives:
    main_obj:
      loss:
        type: "mse"
        track: "mean"
      metric:
        type: "meansquarederror"
      in_config:
        type: "supervised"
        options:
          prediction: "y_pred"
          target: "x_image" # same as input
        dataset: "mnist"

data:
  datasets:
    "mnist":
      in:
        x_image:
          shape: [28, 28, 1]
          dtype: "float32" # this is a cast
      split:
        names: ["train", "val"]

optimize:
  optimizers:
    "main_opt":
      type: "adam"
      options:
        learning_rate: 0.0001
      objectives: ["main_obj"]

hyper_parameters:
  epochs: 5
  dataset:
    batch: 16
    shuffle_buffer: 128

model: "parse_path::./model_config.yml"
