meta:
  data_name: "oxford_iiit_pet"
  experiment_name: "trial_00"
  start_fresh: False

logging:
  console:
    level: "info"
    format_str: null
  file:
    level: "ERROR"
    format_str: null
  track:
    tracker_steps: 30
    tensorboard:
      param_steps: 50

performance:
  objectives:
    # each objective can be a loss, a metric, or a combination of both
    main_obj:
      loss:
        # each loss can only be one loss
        type: "sparse_categorical_crossentropy"
        options: [{ "from_logits": True }]
        track: "mean" # for now, only one description allowed
      in_config:
        type: "supervised"
        options:
          prediction: "y_pred"
          target: "x_image" # same as input
        dataset: "oxford_iiit_pet"

# TODO: this section needs to be redone
data:
  datasets:
    "oxford_iiit_pet":
      in:
        x_image:
          shape: [128, 128, 3]
          dtype: "float32" # this is a cast
      split:
        names: ["train", "val"]

optimize:
  optimizers:
    "main_opt":
      type: "adam"
      options:
        learning_rate: 0.0005
      objectives: ["main_obj"]

hyper_parameters:
  epochs: 50
  dataset:
    batch: 16
    shuffle_buffer: 128 # this should be grouped with batchsize

model: "parse_path::./model_config.yml"
