meta:
  data_name: "mnist"
  experiment_name: "trial_00"
  start_fresh: False

logging:
  console:
    format_str: null
    level: "info"
  file:
    format_str: null
    level: "info"
  track:
    tensorboard:
      param_steps: 50
    tracker_steps: 30

performance:
  objectives:
    "main_obj":
      in_config:
        type: "supervised"
        options:
          prediction: "y_pred"
          target: "y_target"
        dataset: "mnist"
      loss:
        type: "sparse_categorical_crossentropy"
        track: "mean" # for now, only one description allowed
      metric:
        # TODO: change this to metric: [name/type]: options:
        type: "SparseCategoricalAccuracy"
        options: null
    # second_obj:
    #   metric:
    #     type: ["TopKCategoricalAccuracy", "TopKCategoricalAccuracy"]
    #     options: [{"k": 2}, {"k": 3}]
    #   in_config:
    #     type: "supervised"
    #     options:
    #       prediction: "y_pred"
    #       target: "y_target"
    #     dataset: 'mnist'

# TODO: this section needs to be redone
data:
  datasets:
    "mnist":
      in:
        x_image:
          shape: [28, 28, 1]
          dtype: "float32" # this is a cast
        y_target:
          shape: [1, 1]
          dtype: "int32"
          label: True
      split:
        names: ["train", "val", "test"]

optimize:
  optimizers:
    "main_opt":
      objectives: ["main_obj"]
      options:
        learning_rate: 0.0001
      type: "adam"

hyper_parameters:
  dataset:
    shuffle_buffer: 128
    batch: 16
  epochs: 10

model: "parse_path::./model_config.yml"
